# Generated by Django 4.2.3 on 2023-08-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=256, verbose_name="文章标题"),
        ),
    ]
